---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:

- name: drone-s3-cache-pull
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/drone-s3cache:v0.2.0
  settings:
    drone-s3-cache-mode: pull
  environment:
    DRONE_S3_CACHE_AWS_ACCESS_KEY_ID:
      from_secret: DRONE_S3_CACHE_AWS_ACCESS_KEY_ID
    DRONE_S3_CACHE_AWS_SECRET_ACCESS_KEY:
      from_secret: DRONE_S3_CACHE_AWS_SECRET_ACCESS_KEY
    DRONE_S3_CACHE_BUCKET_NAME:
      from_secret: DRONE_S3_CACHE_BUCKET_NAME
  when:
    event:
      - push

- name: build
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt:latest
  commands:
    - /root/entrypoint.sh
    - sbt docker:stage
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: drt_drone
  when:
    branch:
      - ${DRONE_BRANCH}
    event:
      - push
  depends_on:
    - drone-s3-cache-pull

- name: drone-s3-cache-push
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/drone-s3cache:v0.2.0
  settings:
    drone-s3-cache-folders:
      - ./.ivy2
    drone-s3-cache-mode: push
  environment:
    DRONE_S3_CACHE_AWS_ACCESS_KEY_ID:
      from_secret: DRONE_S3_CACHE_AWS_ACCESS_KEY_ID
    DRONE_S3_CACHE_AWS_SECRET_ACCESS_KEY:
      from_secret: DRONE_S3_CACHE_AWS_SECRET_ACCESS_KEY
    DRONE_S3_CACHE_BUCKET_NAME:
      from_secret: DRONE_S3_CACHE_BUCKET_NAME
  when:
    event:
      - push
  depends_on:
    - build

- name: publish
  image: plugins/ecr
  environment:
    AWS_REGION: eu-west-2
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: drt/drt-api-import
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    tags:
      - B${DRONE_BUILD_NUMBER}
      - latest
  when:
    event:
      - push
  depends_on:
    - build

...
