//version                                  = 3.11.1
//runner.dialect                           = scala213
//project.git                              = true
//style                                    = defaultWithAlign
//docstrings.style                         = Asterisk
//docstrings.wrap                          = false
//indentOperator.preset                    = spray
//maxColumn                                = 120
//lineEndings                              = preserve
//rewrite.rules                            = [RedundantParens, SortImports, AvoidInfix]
//indentOperator.exemptScope               = all
//align.preset                             = some
//align.tokens."+"                         = [
//  {
//    code   = "~>"
//    owners = [
//      { regex = "Term.ApplyInfix" }
//    ]
//  },
//  {
//    code   = "%"
//    owners = [
//      { regex = "Term.ApplyInfix" }
//    ]
//  },
//  {
//    code   = "%%"
//    owners = [
//      { regex = "Term.ApplyInfix" }
//    ]
//  }
//]
//literals.hexDigits                       = upper
//literals.hexPrefix                       = lower
//binPack.unsafeCallSite                   = always
//binPack.unsafeDefnSite                   = always
//binPack.indentCallSiteSingleArg          = false
//binPack.indentCallSiteOnce               = true
//binPack.importSelectors                  = unfold
//newlines.avoidForSimpleOverflow          = [slc]
//newlines.source                          = keep
//newlines.beforeMultiline                 = keep
//align.openParenDefnSite                  = false
//align.openParenCallSite                  = false
//align.allowOverflow                      = true
//optIn.breakChainOnFirstMethodDot         = false
//optIn.configStyleArguments               = false
//danglingParentheses.preset               = false
//spaces.inImportCurlyBraces               = true
//fileOverride {
//  "glob:**/*.sbt" {
//    runner.dialect = sbt1
//  }
//}
//rewriteTokens          = {
//  "⇒": "=>"
//  "→": "->"
//  "←": "<-"
//}
//project.layout         = StandardConvention
//

version = 3.11.1
runner.dialect = scala213
project.git = true
project.layout = StandardConvention

maxColumn = 120
lineEndings = preserve
style = defaultWithAlign

docstrings.style = Asterisk
docstrings.wrap = false

spaces.inImportCurlyBraces = true

rewrite.rules = [RedundantParens, SortImports]
rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}

align.preset = some
align.allowOverflow = true
align.openParenDefnSite = false
align.openParenCallSite = false
align.tokens."+"                         = [
  {
    code   = "~>"
    owners = [
      { regex = "Term.ApplyInfix" }
    ]
  },
  {
    code   = "%"
    owners = [
      { regex = "Term.ApplyInfix" }
    ]
  },
  {
    code   = "%%"
    owners = [
      { regex = "Term.ApplyInfix" }
    ]
  }
]

newlines.source = keep
newlines.beforeMultiline = keep
newlines.avoidForSimpleOverflow = [slc]

danglingParentheses.callSite = true
danglingParentheses.defnSite = true

binPack.importSelectors = unfold
binPack.unsafeCallSite = false
binPack.unsafeDefnSite = false

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}